# Generated by Django 3.1 on 2020-09-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipsResults',
        ),
    ]
