# Generated by Django 3.1 on 2020-09-04 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips', '0002_delete_tipsresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('run_dt', models.DateTimeField()),
                ('boh_hours', models.IntegerField()),
                ('foh_hours', models.IntegerField()),
                ('tips_amount', models.IntegerField()),
                ('overtips_amounts', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personeelsnummer', models.CharField(max_length=200)),
                ('naam', models.CharField(max_length=200)),
                ('boh_hours', models.IntegerField()),
                ('foh_hours', models.IntegerField()),
                ('total_hours', models.IntegerField()),
                ('boh_tips', models.IntegerField()),
                ('foh_tips', models.IntegerField()),
                ('total_tips', models.IntegerField()),
                ('tipsrun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tips.tipsrun')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
