# Generated by Django 3.1 on 2020-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_tipsresults_tipsrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipsrun',
            name='locatie',
            field=models.CharField(default='Centraal Station', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipsrun',
            name='week',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
