# Generated by Django 3.1 on 2020-09-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_auto_20200904_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsresults',
            name='tipsrun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.tipsrun'),
        ),
    ]
