# Generated by Django 3.1 on 2020-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_auto_20200904_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipsrun',
            name='boh_tipr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipsrun',
            name='effective_tips',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipsrun',
            name='foh_tipr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
