# Generated by Django 3.1 on 2020-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20200907_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsrun',
            name='boh_tipr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsrun',
            name='foh_tipr',
            field=models.FloatField(),
        ),
    ]
