# Generated by Django 3.1 on 2020-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_auto_20200907_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsresults',
            name='boh_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsresults',
            name='boh_tips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsresults',
            name='foh_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsresults',
            name='foh_tips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsresults',
            name='total_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsresults',
            name='total_tips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsrun',
            name='boh_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsrun',
            name='effective_tips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsrun',
            name='foh_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsrun',
            name='overtips_amounts',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tipsrun',
            name='tips_amount',
            field=models.FloatField(),
        ),
    ]
