# Generated by Django 3.1 on 2020-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locatie',
            field=models.CharField(choices=[('Centraal Station', 'CS'), ('ZUID', 'ZUID')], default='CS', max_length=30),
        ),
    ]
